### ISSUE TITLE
Path to skin diffuse map is not OK

### ISSUE THREAD

**Issue by metal3d** [makehumancommunity/community-plugins-mhapi#5] opened 2019-09-04 09:09 UTC
Hi,

When I'm using the community plugin to download skin assets, the definition files want to use `../textures/xxx` path, but the path of the texture should be `./xxx`

For now, I'm using a script to fixup each downloaded assets, but is this normal ?

**Comment by joepal1976** [comment] 2019-09-13 11:47
This is not an error with MHAPI, which is a programming interface. 

Without having seen what particular skin you are trying to download, I would assume that the problem is that the person who uploaded the asset did so with erronous file paths in the MHMAT file. 

As far as I know, it is not a problem with skins in general.

Errors within particular assets should be reported to the person who created the asset. This either as a comment on the web page for the asset (found from http://www.makehumancommunity.org/content/user_contributed_assets.html), or on the forums. 

Closing this particular issue as off topic for this bug tracker. If you think it is a bug with the asset downloader, open an issue on the asset downloader bug tracker at https://github.com/makehumancommunity/community-plugins-assetdownload/issues

**Closed as completed by joepal1976** 2019-09-13 11:47 UTC

**Comment by metal3d** [comment] 2019-10-04 07:55
It's probably the asset downloader - 95% of skin texture I download has not the right path in file. I will open a bug report later.

Thanks.
