### ISSUE TITLE
from core import G

### ISSUE THREAD

**Issue by charchitd** [makehumancommunity/community-plugins-mhapi#9] opened 2021-04-20 17:22 UTC
please help me, after placing 1_mhapi in plugin dir/ I can't able to execute from core Import G to get the API function working.
![error](https://user-images.githubusercontent.com/30744323/115439154-e1c4da00-a22b-11eb-843a-8ec6714c5594.PNG)

**Comment by Aranuvir** [comment] 2021-04-21 20:56
You cannot access G from outside the MH app. It's a class instance on which data is hooked up during the start sequence. Here is the relevant file: https://github.com/makehumancommunity/makehuman/blob/master/makehuman/lib/core.py

For further help on this topic please contact the forum: http://www.makehumancommunity.org/forum/index.php. 
Here is the bug tracker. Closing, since not a bug.

**Closed as completed by Aranuvir** 2021-04-21 20:56 UTC
Labels: invalid

**Comment by charchitd** [comment] 2021-04-23 06:55
Thank you very much... now I am getting this error. AttributeError: "NoneType" ....
![error1](https://user-images.githubusercontent.com/30744323/115831033-afcf9580-a42e-11eb-91d3-e4f6f0690128.PNG)
Could you please help me with this :(
